import React from "react";

export default function Head(){
    return(
        <React.Fragment>
            <title>Sketch</title>
            <meta content="width=device-width, initial-scale=1" name="viewport"/>
            <meta name="description" content="Generated by Aamish"/>
            <link rel="icon" href="/favicon.ico"/> 
        </React.Fragment>
    );
}